project_id = "qpnzjcbdtybwazceggmv"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.scrape-linkedin]
    verify_jwt = false
  [functions.sync-expert]
    verify_jwt = false
  [functions.attendee-stats]
    verify_jwt = false
  [functions.expert-og]
    verify_jwt = false
